/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.train_ticket.model;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class GUI extends javax.swing.JFrame {
    CardLayout crdlayout;
    public GUI() {
        initComponents();
        crdlayout = new CardLayout();
        panel_holder.setLayout(crdlayout);
        panel_holder.add("CustomerForm",new CustomerForm());
        panel_holder.add("TicketForm",new TicketForm());
        panel_holder.add("BillForm",new BillForm());
        panel_holder.add("SortTicketForm",new SortTicketForm());
        panel_holder.add("SortBillForm",new SortBillForm());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_holder = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        item_customer = new javax.swing.JMenuItem();
        item_ticket = new javax.swing.JMenuItem();
        item_bill = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        item_price = new javax.swing.JMenuItem();
        item_date = new javax.swing.JMenuItem();
        item_money = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        item_sum = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panel_holderLayout = new javax.swing.GroupLayout(panel_holder);
        panel_holder.setLayout(panel_holderLayout);
        panel_holderLayout.setHorizontalGroup(
            panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        panel_holderLayout.setVerticalGroup(
            panel_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        jMenu1.setText("Data");

        item_customer.setText("Customer");
        item_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_customerActionPerformed(evt);
            }
        });
        jMenu1.add(item_customer);

        item_ticket.setText("Ticket");
        item_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_ticketActionPerformed(evt);
            }
        });
        jMenu1.add(item_ticket);

        item_bill.setText("Bill");
        item_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_billActionPerformed(evt);
            }
        });
        jMenu1.add(item_bill);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sort");

        item_price.setText("By Price in Ticket");
        item_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_priceActionPerformed(evt);
            }
        });
        jMenu2.add(item_price);

        item_date.setText("By date in Bill");
        item_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_dateActionPerformed(evt);
            }
        });
        jMenu2.add(item_date);

        item_money.setText("By total money in Bill");
        item_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_moneyActionPerformed(evt);
            }
        });
        jMenu2.add(item_money);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Statistic");

        item_sum.setText("Sum of total money by year");
        jMenu3.add(item_sum);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_customerActionPerformed
        crdlayout.show(panel_holder, "CustomerForm");
    }//GEN-LAST:event_item_customerActionPerformed

    private void item_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_ticketActionPerformed
        crdlayout.show(panel_holder, "TicketForm");
    }//GEN-LAST:event_item_ticketActionPerformed

    private void item_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_billActionPerformed
        crdlayout.show(panel_holder, "BillForm");
    }//GEN-LAST:event_item_billActionPerformed

    private void item_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_priceActionPerformed
        crdlayout.show(panel_holder,"SortTicketForm");
    }//GEN-LAST:event_item_priceActionPerformed

    private void item_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_dateActionPerformed
        crdlayout.show(panel_holder,"SortBillForm");
    }//GEN-LAST:event_item_dateActionPerformed

    private void item_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_moneyActionPerformed
        crdlayout.show(panel_holder,"SortBillForm");
    }//GEN-LAST:event_item_moneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item_bill;
    private javax.swing.JMenuItem item_customer;
    private javax.swing.JMenuItem item_date;
    private javax.swing.JMenuItem item_money;
    private javax.swing.JMenuItem item_price;
    private javax.swing.JMenuItem item_sum;
    private javax.swing.JMenuItem item_ticket;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel panel_holder;
    // End of variables declaration//GEN-END:variables
}
